### ISSUE TITLE
Updated designs

### ISSUE THREAD

**Issue by othnielNgobeni** [Some-Cool-Name/Find-Loverz-WebApp#5]
// Updated designs

https://github.com/Some-Cool-Name/Find-Loverz-WebApp.wiki.git

![Web 1920 – 1](https://user-images.githubusercontent.com/81512981/130837826-fe0aea3d-77a4-4bfb-87bb-5013fcedb09f.png)
![Web 1920 – 1](https://user-images.githubusercontent.com/81512981/130837841-84cf4c7e-b414-45d1-a8fd-70a06815c31e.png)

**Comment by Melissa941** [comment]
![Feed page](https://user-images.githubusercontent.com/76457753/133086054-837d07b8-d169-4bff-9b71-8c295e117a3f.png)

**Comment by Melissa941** [comment]
![Feed page – 1](https://user-images.githubusercontent.com/76457753/133089104-2643b520-35d0-4905-bf3c-1ad7e43f17b5.png)

**Comment by Melissa941** [comment]
![Profile](https://user-images.githubusercontent.com/76457753/133945165-8b66f4de-babf-49ac-aae4-10d9cf01e3bb.png)

**Comment by Melissa941** [comment]
![feed](https://user-images.githubusercontent.com/76457753/136198348-5dfea417-04f4-4579-ba75-e4a5956f34d3.png)
![feed 2](https://user-images.githubusercontent.com/76457753/136198363-446b5de8-a994-455a-81be-506c78b1a553.png)
![feed 3](https://user-images.githubusercontent.com/76457753/136198371-4c2744c7-30d2-4bae-abf7-0707ca64f821.png)

![Edit Profile](https://user-images.githubusercontent.com/76457753/136198379-058f51e7-63a8-48ec-a5d9-b5af2149e7e6.png)
![chats](https://user-images.githubusercontent.com/76457753/136198383-98e72d65-fa71-44c4-917b-142634cd78ed.png)

**Comment by Melissa941** [comment]
![Edit Profile](https://user-images.githubusercontent.com/76457753/136201364-8087dc1f-fc62-45a4-95d7-0fc18cc32d38.png)

**Comment by Melissa941** [comment]
![chats](https://user-images.githubusercontent.com/76457753/136204248-be1cdc3b-02f1-4ce6-ba0b-805869f4aabb.png)
